import * as types from './types';

// Helper function to generate dates relative to today (April 8, 2026)
const baseDate = new Date('2026-04-08T00:00:00Z');
const offsetDate = (days: number) => {
  const d = new Date(baseDate);
  d.setDate(d.getDate() + days);
  return d.toISOString();
};

const departmentList = ['Engineering', 'Product', 'Marketing', 'Legal', 'HR & People', 'Finance', 'Sales'];
const modelList = ['GPT-4o', 'Claude 3.5 Sonnet', 'Gemini Pro', 'Mistral', 'Local Ollama'];
const providerList = ['OpenAI', 'Anthropic', 'Google', 'Mistral', 'Local'];

// Dashboard Summary
export const mockDashboardSummary: types.DashboardSummary = {
  period: '2026-04-01 to 2026-04-08',
  generatedAt: baseDate.toISOString(),
  metrics: {
    totalCost: 47832.50,
    totalEvents: 12847,
    totalTokens: 2847392,
    totalDepartments: 7,
    totalModels: 5,
  },
  findings: {
    totalFindings: 54,
    criticalCount: 13,
    highCount: 34,
    mediumCount: 72,
    categoryCounts: {
      secrets: 46,
      pii: 46,
      slopsquat: 27,
    },
  },
  compliance: {
    complianceScore: 78,
    status: 'yellow',
  },
  anomalies: 3,
  topDepartments: [
    { department: 'Engineering', cost: 18200.00, events: 4928 },
    { department: 'Product', cost: 8400.00, events: 2341 },
    { department: 'Sales', cost: 6750.00, events: 1847 },
    { department: 'Marketing', cost: 5320.00, events: 1521 },
    { department: 'Finance', cost: 4890.00, events: 1298 },
  ],
};

// Compliance Score
export const mockComplianceScore: types.ComplianceScore = {
  overallScore: 78,
  status: 'partial',
  auditPillars: [
    {
      check: 'Data Minimization',
      description: 'Ensuring only necessary data is shared with providers',
      compliancePercentage: 85,
      recordsCovering: 8923,
      totalRecords: 10492,
    },
    {
      check: 'Consent Management',
      description: 'Proper user consent for data processing',
      compliancePercentage: 92,
      recordsCovering: 9654,
      totalRecords: 10492,
    },
    {
      check: 'Encryption & Security',
      description: 'Data encrypted in transit and at rest',
      compliancePercentage: 78,
      recordsCovering: 8182,
      totalRecords: 10492,
    },
    {
      check: 'Vendor Risk Management',
      description: 'Third-party provider compliance verification',
      compliancePercentage: 65,
      recordsCovering: 6820,
      totalRecords: 10492,
    },
    {
      check: 'Audit Logging',
      description: 'Complete audit trail of data access and modifications',
      compliancePercentage: 88,
      recordsCovering: 9233,
      totalRecords: 10492,
    },
    {
      check: 'Data Retention',
      description: 'Data deleted within retention policy timeframes',
      compliancePercentage: 72,
      recordsCovering: 7554,
      totalRecords: 10492,
    },
  ],
  lastAudited: offsetDate(-2),
};

// Cost by Department
export const mockCostByDepartment: types.CostBucket[] = [
  {
    key: 'Engineering',
    cost: 18200.00,
    sessions: 892,
    avgCostPerSession: 20.40,
    events: 4928,
    tokens: 1128932,
    costPerToken: 0.0161,
    trivialPercentage: 12,
    privatePercentage: 28,
  },
  {
    key: 'Product',
    cost: 8400.00,
    sessions: 412,
    avgCostPerSession: 20.39,
    events: 2341,
    tokens: 521847,
    costPerToken: 0.0161,
    trivialPercentage: 14,
    privatePercentage: 31,
  },
  {
    key: 'Sales',
    cost: 6750.00,
    sessions: 328,
    avgCostPerSession: 20.58,
    events: 1847,
    tokens: 418293,
    costPerToken: 0.0161,
    trivialPercentage: 18,
    privatePercentage: 35,
  },
  {
    key: 'Marketing',
    cost: 5320.00,
    sessions: 251,
    avgCostPerSession: 21.19,
    events: 1521,
    tokens: 329847,
    costPerToken: 0.0161,
    trivialPercentage: 16,
    privatePercentage: 29,
  },
  {
    key: 'Finance',
    cost: 4890.00,
    sessions: 238,
    avgCostPerSession: 20.55,
    events: 1298,
    tokens: 293847,
    costPerToken: 0.0167,
    trivialPercentage: 10,
    privatePercentage: 22,
  },
  {
    key: 'Legal',
    cost: 2340.00,
    sessions: 112,
    avgCostPerSession: 20.89,
    events: 618,
    tokens: 108293,
    costPerToken: 0.0216,
    trivialPercentage: 8,
    privatePercentage: 18,
  },
  {
    key: 'HR & People',
    cost: 1132.50,
    sessions: 68,
    avgCostPerSession: 16.65,
    events: 294,
    tokens: 46341,
    costPerToken: 0.0244,
    trivialPercentage: 9,
    privatePercentage: 19,
  },
];

// Cost by Model
export const mockCostByModel: types.CostBucket[] = [
  {
    key: 'GPT-4o',
    cost: 22100.00,
    sessions: 1087,
    avgCostPerSession: 20.33,
    events: 6234,
    tokens: 1432847,
    costPerToken: 0.0154,
    trivialPercentage: 14,
    privatePercentage: 30,
  },
  {
    key: 'Claude 3.5 Sonnet',
    cost: 14200.00,
    sessions: 692,
    avgCostPerSession: 20.52,
    events: 3921,
    tokens: 892341,
    costPerToken: 0.0159,
    trivialPercentage: 13,
    privatePercentage: 28,
  },
  {
    key: 'Gemini Pro',
    cost: 6800.00,
    sessions: 338,
    avgCostPerSession: 20.12,
    events: 1847,
    tokens: 412847,
    costPerToken: 0.0165,
    trivialPercentage: 15,
    privatePercentage: 32,
  },
  {
    key: 'Mistral',
    cost: 3100.00,
    sessions: 152,
    avgCostPerSession: 20.39,
    events: 721,
    tokens: 187293,
    costPerToken: 0.0165,
    trivialPercentage: 12,
    privatePercentage: 25,
  },
  {
    key: 'Local Ollama',
    cost: 1632.50,
    sessions: 78,
    avgCostPerSession: 20.93,
    events: 124,
    tokens: 52064,
    costPerToken: 0.0314,
    trivialPercentage: 11,
    privatePercentage: 20,
  },
];

// Cost Time Series (12 weeks)
export const mockCostTimeSeries: types.TimeSeriesResponse = {
  metric: 'daily_cost',
  granularity: 'day',
  data: Array.from({ length: 85 }, (_, i) => ({
    timestamp: offsetDate(i - 84),
    value: 3200 + Math.random() * 1200 + i * 15,
  })),
};

// Severity Distribution
export const mockSeverityDistribution: types.SeverityDistribution = {
  secrets: {
    critical: 8,
    high: 15,
    medium: 23,
  },
  pii: {
    critical: 3,
    high: 12,
    medium: 31,
  },
  slopsquat: {
    critical: 2,
    high: 7,
    medium: 18,
  },
};

// Findings
export const mockFindings: types.Finding[] = [
  {
    id: 'find_001',
    type: 'secret',
    severity: 'critical',
    category: 'AWS Credentials',
    detectedAt: offsetDate(-3),
    department: 'Engineering',
    user: 'alice.chen@company.com',
    provider: 'OpenAI',
    conversationId: 'conv_001',
    status: 'open',
    matchValue: 'AKIA3E...',
    contextPreview: "...config.set('aws_secret_access_key', 'AKIA3E8K9H2L4M1N5P8Q...[REDACTED]')...",
    confidence: 0.98,
  },
  {
    id: 'find_002',
    type: 'pii',
    severity: 'critical',
    category: 'Credit Card Number',
    detectedAt: offsetDate(-2),
    department: 'Finance',
    user: 'robert.schmidt@company.com',
    provider: 'Claude',
    conversationId: 'conv_002',
    status: 'open',
    matchValue: '4532...',
    contextPreview: '...payment processed for 4532 1234 5678 9012 ...[REDACTED]...',
    confidence: 0.99,
  },
  {
    id: 'find_003',
    type: 'slopsquat',
    severity: 'high',
    category: 'Fabricated Package Name',
    detectedAt: offsetDate(-4),
    department: 'Engineering',
    user: 'alice.chen@company.com',
    provider: 'GPT-4o',
    conversationId: 'conv_003',
    status: 'acknowledged',
    matchValue: 'aws-credential-mgr',
    contextPreview: '...suggested to install aws-credential-mgr from npm...',
    confidence: 0.92,
  },
  {
    id: 'find_004',
    type: 'secret',
    severity: 'high',
    category: 'GitHub Token',
    detectedAt: offsetDate(-1),
    department: 'Engineering',
    user: 'david.mueller@company.com',
    provider: 'Claude',
    conversationId: 'conv_004',
    status: 'open',
    matchValue: 'ghp_...',
    contextPreview: '...export GITHUB_TOKEN=ghp_abcdef123456...[REDACTED]...',
    confidence: 0.95,
  },
  {
    id: 'find_005',
    type: 'pii',
    severity: 'high',
    category: 'Social Security Number',
    detectedAt: offsetDate(-5),
    department: 'HR & People',
    user: 'sarah.johnson@company.com',
    provider: 'Gemini',
    conversationId: 'conv_005',
    status: 'resolved',
    matchValue: '123-45-...',
    contextPreview: '...employee SSN 123-45-6789 in the system...[REDACTED]...',
    confidence: 0.99,
  },
  {
    id: 'find_006',
    type: 'secret',
    severity: 'medium',
    category: 'Database Password',
    detectedAt: offsetDate(-6),
    department: 'Engineering',
    user: 'alice.chen@company.com',
    provider: 'GPT-4o',
    conversationId: 'conv_006',
    status: 'open',
    matchValue: 'postgres://...',
    contextPreview: '...postgres://user:password@db.internal.com/prod...[REDACTED]...',
    confidence: 0.87,
  },
  {
    id: 'find_007',
    type: 'pii',
    severity: 'medium',
    category: 'Email Address',
    detectedAt: offsetDate(-7),
    department: 'Sales',
    user: 'james.wilson@company.com',
    provider: 'Claude',
    conversationId: 'conv_007',
    status: 'open',
    matchValue: 'customer@...',
    contextPreview: '...customer email john.doe@privatecorp.com exposed...',
    confidence: 0.76,
  },
  {
    id: 'find_008',
    type: 'slopsquat',
    severity: 'medium',
    category: 'Fabricated CLI Tool',
    detectedAt: offsetDate(-8),
    department: 'Engineering',
    user: 'maria.garcia@company.com',
    provider: 'GPT-4o',
    conversationId: 'conv_008',
    status: 'open',
    matchValue: 'kubectl-security-scan',
    contextPreview: '...suggested kubectl-security-scan is a real tool...',
    confidence: 0.88,
  },
  {
    id: 'find_009',
    type: 'secret',
    severity: 'critical',
    category: 'API Key',
    detectedAt: offsetDate(-9),
    department: 'Product',
    user: 'emma.taylor@company.com',
    provider: 'Claude',
    conversationId: 'conv_009',
    status: 'open',
    matchValue: 'sk-...',
    contextPreview: '...OpenAI API key sk_live_abc123def456...[REDACTED]...',
    confidence: 0.99,
  },
  {
    id: 'find_010',
    type: 'pii',
    severity: 'high',
    category: 'Phone Number',
    detectedAt: offsetDate(-10),
    department: 'Marketing',
    user: 'lucas.martin@company.com',
    provider: 'Gemini',
    conversationId: 'conv_010',
    status: 'acknowledged',
    matchValue: '+1 555...',
    contextPreview: '...contact number +1 555-867-5309 for customer...',
    confidence: 0.82,
  },
  {
    id: 'find_011',
    type: 'secret',
    severity: 'high',
    category: 'Private Key',
    detectedAt: offsetDate(-11),
    department: 'Engineering',
    user: 'alice.chen@company.com',
    provider: 'GPT-4o',
    conversationId: 'conv_011',
    status: 'open',
    matchValue: '-----BEGIN RSA PRIVATE KEY-----',
    contextPreview: '...-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA...[REDACTED]...',
    confidence: 0.99,
  },
  {
    id: 'find_012',
    type: 'slopsquat',
    severity: 'high',
    category: 'Fabricated RBAC Role',
    detectedAt: offsetDate(-12),
    department: 'Engineering',
    user: 'david.mueller@company.com',
    provider: 'Claude',
    conversationId: 'conv_012',
    status: 'open',
    matchValue: 'kubernetes-admin-proxy',
    contextPreview: '...role kubernetes-admin-proxy with elevated permissions...',
    confidence: 0.91,
  },
  {
    id: 'find_013',
    type: 'pii',
    severity: 'medium',
    category: 'Home Address',
    detectedAt: offsetDate(-13),
    department: 'HR & People',
    user: 'sarah.johnson@company.com',
    provider: 'Claude',
    conversationId: 'conv_013',
    status: 'open',
    matchValue: '123 Main St...',
    contextPreview: '...employee address 123 Main Street, Springfield IL...[REDACTED]...',
    confidence: 0.75,
  },
  {
    id: 'find_014',
    type: 'secret',
    severity: 'medium',
    category: 'JWT Token',
    detectedAt: offsetDate(-14),
    department: 'Engineering',
    user: 'maria.garcia@company.com',
    provider: 'Mistral',
    conversationId: 'conv_014',
    status: 'resolved',
    matchValue: 'eyJhbGc...',
    contextPreview: '...Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...[REDACTED]...',
    confidence: 0.85,
  },
  {
    id: 'find_015',
    type: 'pii',
    severity: 'critical',
    category: 'Passport Number',
    detectedAt: offsetDate(-15),
    department: 'Finance',
    user: 'robert.schmidt@company.com',
    provider: 'Gemini',
    conversationId: 'conv_015',
    status: 'open',
    matchValue: 'A1234567',
    contextPreview: '...passport A1234567 for international travel...[REDACTED]...',
    confidence: 0.97,
  },
  {
    id: 'find_016',
    type: 'secret',
    severity: 'high',
    category: 'Slack Token',
    detectedAt: offsetDate(-16),
    department: 'Product',
    user: 'emma.taylor@company.com',
    provider: 'Claude',
    conversationId: 'conv_016',
    status: 'open',
    matchValue: 'xoxb-...',
    contextPreview: '...Slack bot token xoxb_abc123def456ghi789...[REDACTED]...',
    confidence: 0.96,
  },
  {
    id: 'find_017',
    type: 'slopsquat',
    severity: 'medium',
    category: 'Fabricated Endpoint',
    detectedAt: offsetDate(-17),
    department: 'Product',
    user: 'james.anderson@company.com',
    provider: 'GPT-4o',
    conversationId: 'conv_017',
    status: 'open',
    matchValue: 'api.kubernetes.internal',
    contextPreview: '...internal endpoint api.kubernetes.internal (non-existent)...',
    confidence: 0.80,
  },
  {
    id: 'find_018',
    type: 'pii',
    severity: 'medium',
    category: 'Date of Birth',
    detectedAt: offsetDate(-18),
    department: 'Legal',
    user: 'christine.brown@company.com',
    provider: 'Claude',
    conversationId: 'conv_018',
    status: 'acknowledged',
    matchValue: '1985-06-15',
    contextPreview: '...employee DOB 1985-06-15 in personnel file...',
    confidence: 0.79,
  },
  {
    id: 'find_019',
    type: 'secret',
    severity: 'critical',
    category: 'Database Connection String',
    detectedAt: offsetDate(-19),
    department: 'Engineering',
    user: 'alice.chen@company.com',
    provider: 'GPT-4o',
    conversationId: 'conv_019',
    status: 'open',
    matchValue: 'mongodb+srv://...',
    contextPreview: '...mongodb+srv://admin:password123@cluster.mongodb.net/prod...[REDACTED]...',
    confidence: 0.99,
  },
  {
    id: 'find_020',
    type: 'pii',
    severity: 'high',
    category: 'Bank Account Number',
    detectedAt: offsetDate(-20),
    department: 'Finance',
    user: 'robert.schmidt@company.com',
    provider: 'Claude',
    conversationId: 'conv_020',
    status: 'open',
    matchValue: 'DE89...',
    contextPreview: '...bank account DE89 3704 0044 0532 0130 00 for...[REDACTED]...',
    confidence: 0.98,
  },
];

// Alerts
export const mockAlerts: types.Alert[] = [
  {
    id: 'alert_001',
    type: 'secret',
    severity: 'critical',
    title: 'Critical: AWS Access Key Detected',
    message: 'AWS access key exposed in Engineering department conversation',
    timestamp: offsetDate(-0.5),
    department: 'Engineering',
    provider: 'OpenAI',
    conversationId: 'conv_001',
    status: 'new',
    actionUrl: '/findings/find_001',
  },
  {
    id: 'alert_002',
    type: 'pii',
    severity: 'critical',
    title: 'Critical: Payment Card Detected',
    message: 'Credit card number found in Finance department logs',
    timestamp: offsetDate(-1),
    department: 'Finance',
    provider: 'Claude',
    conversationId: 'conv_002',
    status: 'new',
    actionUrl: '/findings/find_002',
  },
  {
    id: 'alert_003',
    type: 'slopsquat',
    severity: 'high',
    title: 'High: Fabricated Package Referenced',
    message: 'Non-existent npm package aws-credential-mgr suggested',
    timestamp: offsetDate(-2),
    department: 'Engineering',
    provider: 'GPT-4o',
    conversationId: 'conv_003',
    status: 'acknowledged',
    actionUrl: '/findings/find_003',
  },
  {
    id: 'alert_004',
    type: 'secret',
    severity: 'high',
    title: 'High: GitHub Token Exposed',
    message: 'GitHub personal access token found in conversation',
    timestamp: offsetDate(-2.5),
    department: 'Engineering',
    provider: 'Claude',
    conversationId: 'conv_004',
    status: 'new',
    actionUrl: '/findings/find_004',
  },
  {
    id: 'alert_005',
    type: 'pii',
    severity: 'high',
    title: 'High: SSN Detected',
    message: 'Social Security number found in HR conversation',
    timestamp: offsetDate(-3),
    department: 'HR & People',
    provider: 'Gemini',
    conversationId: 'conv_005',
    status: 'resolved',
    actionUrl: '/findings/find_005',
  },
  {
    id: 'alert_006',
    type: 'secret',
    severity: 'high',
    title: 'High: Database Credentials Exposed',
    message: 'PostgreSQL connection string with credentials detected',
    timestamp: offsetDate(-3.5),
    department: 'Engineering',
    provider: 'GPT-4o',
    conversationId: 'conv_006',
    status: 'new',
    actionUrl: '/findings/find_006',
  },
  {
    id: 'alert_007',
    type: 'pii',
    severity: 'medium',
    title: 'Medium: Email Address Exposed',
    message: 'Customer email address found in sales conversation',
    timestamp: offsetDate(-4),
    department: 'Sales',
    provider: 'Claude',
    conversationId: 'conv_007',
    status: 'new',
    actionUrl: '/findings/find_007',
  },
  {
    id: 'alert_008',
    type: 'slopsquat',
    severity: 'medium',
    title: 'Medium: Fabricated CLI Tool',
    message: 'Non-existent Kubernetes CLI tool referenced',
    timestamp: offsetDate(-4.5),
    department: 'Engineering',
    provider: 'GPT-4o',
    conversationId: 'conv_008',
    status: 'new',
    actionUrl: '/findings/find_008',
  },
  {
    id: 'alert_009',
    type: 'secret',
    severity: 'critical',
    title: 'Critical: API Key Exposed',
    message: 'OpenAI API key leaked in Product department',
    timestamp: offsetDate(-5),
    department: 'Product',
    provider: 'Claude',
    conversationId: 'conv_009',
    status: 'new',
    actionUrl: '/findings/find_009',
  },
  {
    id: 'alert_010',
    type: 'pii',
    severity: 'high',
    title: 'High: Phone Number Exposed',
    message: 'Customer phone number found in marketing materials',
    timestamp: offsetDate(-5.5),
    department: 'Marketing',
    provider: 'Gemini',
    conversationId: 'conv_010',
    status: 'acknowledged',
    actionUrl: '/findings/find_010',
  },
  {
    id: 'alert_011',
    type: 'secret',
    severity: 'critical',
    title: 'Critical: Private Key Detected',
    message: 'RSA private key exposed in code conversation',
    timestamp: offsetDate(-6),
    department: 'Engineering',
    provider: 'GPT-4o',
    conversationId: 'conv_011',
    status: 'new',
    actionUrl: '/findings/find_011',
  },
  {
    id: 'alert_012',
    type: 'slopsquat',
    severity: 'high',
    title: 'High: Fabricated RBAC Role',
    message: 'Non-existent Kubernetes RBAC role suggested',
    timestamp: offsetDate(-6.5),
    department: 'Engineering',
    provider: 'Claude',
    conversationId: 'conv_012',
    status: 'new',
    actionUrl: '/findings/find_012',
  },
  {
    id: 'alert_013',
    type: 'pii',
    severity: 'medium',
    title: 'Medium: Address Information Exposed',
    message: 'Employee home address found in HR files',
    timestamp: offsetDate(-7),
    department: 'HR & People',
    provider: 'Claude',
    conversationId: 'conv_013',
    status: 'new',
    actionUrl: '/findings/find_013',
  },
  {
    id: 'alert_014',
    type: 'secret',
    severity: 'medium',
    title: 'Medium: JWT Token Exposed',
    message: 'JSON Web Token found in conversation logs',
    timestamp: offsetDate(-7.5),
    department: 'Engineering',
    provider: 'Mistral',
    conversationId: 'conv_014',
    status: 'resolved',
    actionUrl: '/findings/find_014',
  },
  {
    id: 'alert_015',
    type: 'pii',
    severity: 'critical',
    title: 'Critical: Passport Information',
    message: 'International passport number exposed',
    timestamp: offsetDate(-8),
    department: 'Finance',
    provider: 'Gemini',
    conversationId: 'conv_015',
    status: 'new',
    actionUrl: '/findings/find_015',
  },
];

// Model Metrics
export const mockModelMetrics: types.ModelMetrics[] = [
  {
    model: 'GPT-4o',
    provider: 'OpenAI',
    usage: { events: 6234, tokens: 1432847, sessions: 1087 },
    costs: { total: 22100.00, perToken: 0.0154, perSession: 20.33 },
    risk: { leakCount: 12, leakRate: 0.192, hallucRate: 0.034 },
    costPerQualityRatio: 0.98,
  },
  {
    model: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    usage: { events: 3921, tokens: 892341, sessions: 692 },
    costs: { total: 14200.00, perToken: 0.0159, perSession: 20.52 },
    risk: { leakCount: 6, leakRate: 0.153, hallucRate: 0.011 },
    costPerQualityRatio: 0.85,
  },
  {
    model: 'Gemini Pro',
    provider: 'Google',
    usage: { events: 1847, tokens: 412847, sessions: 338 },
    costs: { total: 6800.00, perToken: 0.0165, perSession: 20.12 },
    risk: { leakCount: 8, leakRate: 0.433, hallucRate: 0.028 },
    costPerQualityRatio: 1.15,
  },
  {
    model: 'Mistral',
    provider: 'Mistral',
    usage: { events: 721, tokens: 187293, sessions: 152 },
    costs: { total: 3100.00, perToken: 0.0165, perSession: 20.39 },
    risk: { leakCount: 3, leakRate: 0.416, hallucRate: 0.019 },
    costPerQualityRatio: 1.42,
  },
  {
    model: 'Local Ollama',
    provider: 'Local',
    usage: { events: 124, tokens: 52064, sessions: 78 },
    costs: { total: 1632.50, perToken: 0.0314, perSession: 20.93 },
    risk: { leakCount: 0, leakRate: 0.0, hallucRate: 0.005 },
    costPerQualityRatio: 2.18,
  },
];

// Slopsquatting Stats by Model
export const mockSlopsquattingStats: types.SlopsquattingStats[] = [
  {
    provider: 'GPT-4o',
    hallucCount: 187,
    hallucRate: 4.2,
    fabricationTypes: {
      packages: 72,
      endpoints: 48,
      cliTools: 34,
      rbacRoles: 33,
    },
    topHallucinations: [
      { name: 'aws-credential-mgr', type: 'package', count: 23 },
      { name: 'kubectl-security-scan', type: 'cliTools', count: 18 },
      { name: 'api.kubernetes.internal', type: 'endpoints', count: 14 },
      { name: 'kubernetes-admin-proxy', type: 'rbacRoles', count: 12 },
    ],
  },
  {
    provider: 'Claude 3.5 Sonnet',
    hallucCount: 42,
    hallucRate: 1.1,
    fabricationTypes: {
      packages: 18,
      endpoints: 12,
      cliTools: 8,
      rbacRoles: 4,
    },
    topHallucinations: [
      { name: 'data-verification-lib', type: 'package', count: 6 },
      { name: 'internal-auth-svc', type: 'endpoints', count: 4 },
    ],
  },
  {
    provider: 'Gemini Pro',
    hallucCount: 89,
    hallucRate: 3.8,
    fabricationTypes: {
      packages: 34,
      endpoints: 28,
      cliTools: 18,
      rbacRoles: 9,
    },
    topHallucinations: [
      { name: 'npm-auth-token-manager', type: 'package', count: 15 },
      { name: 'secure-env-loader', type: 'package', count: 12 },
    ],
  },
  {
    provider: 'Mistral',
    hallucCount: 31,
    hallucRate: 2.1,
    fabricationTypes: {
      packages: 12,
      endpoints: 10,
      cliTools: 6,
      rbacRoles: 3,
    },
    topHallucinations: [
      { name: 'config-manager-pro', type: 'package', count: 5 },
    ],
  },
  {
    provider: 'Local Ollama',
    hallucCount: 2,
    hallucRate: 0.3,
    fabricationTypes: {
      packages: 1,
      endpoints: 0,
      cliTools: 1,
      rbacRoles: 0,
    },
    topHallucinations: [
      { name: 'test-lib', type: 'package', count: 1 },
    ],
  },
];

// Data Flow (Sankey)
export const mockDataFlow: types.DataFlowResponse = {
  nodes: [
    // Departments
    { id: 'dept_eng', label: 'Engineering', type: 'department' },
    { id: 'dept_prod', label: 'Product', type: 'department' },
    { id: 'dept_sales', label: 'Sales', type: 'department' },
    { id: 'dept_marketing', label: 'Marketing', type: 'department' },
    // Tools
    { id: 'tool_composer', label: 'ChatComposer', type: 'tool' },
    { id: 'tool_assist', label: 'CodeAssist', type: 'tool' },
    { id: 'tool_summary', label: 'SummaryBot', type: 'tool' },
    // Models
    { id: 'model_gpt4', label: 'GPT-4o', type: 'model' },
    { id: 'model_claude', label: 'Claude 3.5', type: 'model' },
    { id: 'model_gemini', label: 'Gemini Pro', type: 'model' },
    // Regions
    { id: 'region_eu', label: 'EU-West', type: 'region' },
    { id: 'region_us_east', label: 'US-East', type: 'region' },
    { id: 'region_us_west', label: 'US-West', type: 'region' },
  ],
  links: [
    // Departments to Tools
    { source: 'dept_eng', target: 'tool_assist', value: 2800 },
    { source: 'dept_eng', target: 'tool_composer', value: 1920 },
    { source: 'dept_prod', target: 'tool_composer', value: 1200 },
    { source: 'dept_prod', target: 'tool_summary', value: 890 },
    { source: 'dept_sales', target: 'tool_composer', value: 1100 },
    { source: 'dept_marketing', target: 'tool_summary', value: 980 },
    // Tools to Models
    { source: 'tool_assist', target: 'model_gpt4', value: 2200 },
    { source: 'tool_assist', target: 'model_claude', value: 600 },
    { source: 'tool_composer', target: 'model_claude', value: 1800 },
    { source: 'tool_composer', target: 'model_gpt4', value: 1320 },
    { source: 'tool_summary', target: 'model_gemini', value: 1200 },
    { source: 'tool_summary', target: 'model_claude', value: 670 },
    // Models to Regions
    { source: 'model_gpt4', target: 'region_us_east', value: 3520 },
    { source: 'model_claude', target: 'region_eu', value: 3070 },
    { source: 'model_gemini', target: 'region_us_west', value: 1200 },
  ],
};

// Context Risk Sessions
export const mockContextRisk: types.ContextExposureSession[] = [
  {
    sessionId: 'sess_001',
    riskScore: 0.92,
    department: 'Engineering',
    provider: 'GPT-4o',
    filesAccessedCount: 42,
    sensitiveFileTypes: ['*.pem', '*.key', '.env', 'config.json'],
    duration: '2h 34m',
    tokenCount: 89234,
    foundFindings: 3,
    exposureBreakdown: { secrets: 2, pii: 1, slopsquat: 0 },
  },
  {
    sessionId: 'sess_002',
    riskScore: 0.87,
    department: 'Finance',
    provider: 'Claude',
    filesAccessedCount: 28,
    sensitiveFileTypes: ['*.xlsx', '*.pdf', '*.csv'],
    duration: '1h 45m',
    tokenCount: 67432,
    foundFindings: 2,
    exposureBreakdown: { secrets: 0, pii: 2, slopsquat: 0 },
  },
  {
    sessionId: 'sess_003',
    riskScore: 0.81,
    department: 'Engineering',
    provider: 'Claude',
    filesAccessedCount: 35,
    sensitiveFileTypes: ['*.sql', '*.yaml', 'Dockerfile'],
    duration: '3h 12m',
    tokenCount: 123456,
    foundFindings: 1,
    exposureBreakdown: { secrets: 1, pii: 0, slopsquat: 0 },
  },
  {
    sessionId: 'sess_004',
    riskScore: 0.78,
    department: 'HR & People',
    provider: 'Gemini',
    filesAccessedCount: 18,
    sensitiveFileTypes: ['*.docx', '*.xls', 'personnel_db'],
    duration: '1h 23m',
    tokenCount: 45678,
    foundFindings: 2,
    exposureBreakdown: { secrets: 0, pii: 2, slopsquat: 0 },
  },
  {
    sessionId: 'sess_005',
    riskScore: 0.72,
    department: 'Product',
    provider: 'Claude',
    filesAccessedCount: 22,
    sensitiveFileTypes: ['*.env', 'secrets.yaml'],
    duration: '2h 08m',
    tokenCount: 78945,
    foundFindings: 1,
    exposureBreakdown: { secrets: 1, pii: 0, slopsquat: 0 },
  },
  {
    sessionId: 'sess_006',
    riskScore: 0.68,
    department: 'Engineering',
    provider: 'GPT-4o',
    filesAccessedCount: 31,
    sensitiveFileTypes: ['*.tf', '*.json'],
    duration: '2h 45m',
    tokenCount: 92123,
    foundFindings: 1,
    exposureBreakdown: { secrets: 1, pii: 0, slopsquat: 0 },
  },
  {
    sessionId: 'sess_007',
    riskScore: 0.64,
    department: 'Marketing',
    provider: 'Claude',
    filesAccessedCount: 15,
    sensitiveFileTypes: ['*.md', '*.txt'],
    duration: '1h 30m',
    tokenCount: 52341,
    foundFindings: 0,
    exposureBreakdown: { secrets: 0, pii: 0, slopsquat: 0 },
  },
  {
    sessionId: 'sess_008',
    riskScore: 0.61,
    department: 'Engineering',
    provider: 'Mistral',
    filesAccessedCount: 25,
    sensitiveFileTypes: ['*.py', '*.js'],
    duration: '1h 50m',
    tokenCount: 68234,
    foundFindings: 1,
    exposureBreakdown: { secrets: 0, pii: 0, slopsquat: 1 },
  },
  {
    sessionId: 'sess_009',
    riskScore: 0.58,
    department: 'Sales',
    provider: 'Claude',
    filesAccessedCount: 12,
    sensitiveFileTypes: ['*.pdf', 'contact_db'],
    duration: '1h 15m',
    tokenCount: 41293,
    foundFindings: 0,
    exposureBreakdown: { secrets: 0, pii: 0, slopsquat: 0 },
  },
  {
    sessionId: 'sess_010',
    riskScore: 0.55,
    department: 'Engineering',
    provider: 'Claude',
    filesAccessedCount: 19,
    sensitiveFileTypes: ['*.go', '*.rs'],
    duration: '2h 05m',
    tokenCount: 75432,
    foundFindings: 0,
    exposureBreakdown: { secrets: 0, pii: 0, slopsquat: 0 },
  },
];

// Provider DPA
export const mockProviderDPA: types.ProviderComplianceMetadata[] = [
  {
    provider: 'OpenAI',
    regions: ['US-East', 'US-West'],
    dataRetention: { days: 30, policy: 'Automatic deletion after 30 days' },
    hasGDPRDPA: false,
    hasBizAssociate: true,
    jurisdictions: ['United States'],
    riskLevel: 'medium',
    recommendations: [
      'Enable SOC 2 compliance verification',
      'Review data processing agreements',
    ],
  },
  {
    provider: 'Anthropic',
    regions: ['US-East', 'US-West'],
    dataRetention: { days: 30, policy: 'Automatic deletion after 30 days' },
    hasGDPRDPA: true,
    hasBizAssociate: true,
    jurisdictions: ['United States', 'European Union'],
    riskLevel: 'low',
    recommendations: [
      'Continue current compliance monitoring',
    ],
  },
  {
    provider: 'Google',
    regions: ['US-East', 'US-West', 'EU-West'],
    dataRetention: { days: 30, policy: 'Automatic deletion after 30 days' },
    hasGDPRDPA: true,
    hasBizAssociate: false,
    jurisdictions: ['United States', 'European Union'],
    riskLevel: 'low',
    recommendations: [
      'Ensure proper Business Associate Agreement is in place',
    ],
  },
  {
    provider: 'Mistral',
    regions: ['EU-West'],
    dataRetention: { days: 0, policy: 'No data retention (immediately deleted)' },
    hasGDPRDPA: true,
    hasBizAssociate: false,
    jurisdictions: ['European Union'],
    riskLevel: 'low',
    recommendations: [
      'Monitor GDPR compliance closely',
    ],
  },
  {
    provider: 'Local (Ollama)',
    regions: ['On-Premise'],
    dataRetention: { days: 0, policy: 'Under customer control' },
    hasGDPRDPA: true,
    hasBizAssociate: false,
    jurisdictions: ['Customer-defined'],
    riskLevel: 'low',
    recommendations: [
      'Ensure proper data governance policies',
    ],
  },
];

// Recommendations
export const mockRecommendations: types.Recommendation[] = [
  {
    id: 'rec_001',
    category: 'cost_optimization',
    title: 'Optimize GPT-4o Usage in Engineering',
    description: 'Replace 30% of GPT-4o calls with Claude 3.5 Sonnet, which has similar quality but lower cost',
    impact: {
      estimatedSavings: 2840.00,
      riskReduction: 'medium',
      effortToImplement: 'medium',
    },
    actions: [
      'Analyze GPT-4o call patterns',
      'Identify suitable use cases for Claude',
      'Update routing logic',
      'Monitor quality metrics',
    ],
  },
  {
    id: 'rec_002',
    category: 'risk_reduction',
    title: 'Implement Secret Rotation Policy',
    description: 'Establish automated secret rotation for all exposed credentials',
    impact: {
      estimatedSavings: 0,
      riskReduction: 'high',
      effortToImplement: 'hard',
    },
    actions: [
      'Design rotation workflow',
      'Implement automation',
      'Notify affected teams',
      'Monitor for compliance',
    ],
  },
  {
    id: 'rec_003',
    category: 'compliance_improvement',
    title: 'Complete DPA with Google Cloud',
    description: 'Establish formal Data Processing Agreement with Google to achieve 100% GDPR compliance',
    impact: {
      estimatedSavings: 0,
      riskReduction: 'low',
      effortToImplement: 'easy',
    },
    actions: [
      'Review Google standard DPA',
      'Negotiate custom terms if needed',
      'Execute agreement',
      'Document compliance',
    ],
  },
  {
    id: 'rec_004',
    category: 'cost_optimization',
    title: 'Migrate Dev/Test to Local Ollama',
    description: 'Use local LLMs for development and testing environments instead of cloud APIs',
    impact: {
      estimatedSavings: 5200.00,
      riskReduction: 'low',
      effortToImplement: 'medium',
    },
    actions: [
      'Set up Ollama infrastructure',
      'Evaluate model performance',
      'Update CI/CD pipelines',
      'Migrate development workflows',
    ],
  },
  {
    id: 'rec_005',
    category: 'risk_reduction',
    title: 'Enforce Context Access Controls',
    description: 'Implement file-level access restrictions to prevent sensitive file exposure in AI contexts',
    impact: {
      estimatedSavings: 0,
      riskReduction: 'high',
      effortToImplement: 'hard',
    },
    actions: [
      'Audit current file access patterns',
      'Design access control framework',
      'Implement enforcement mechanisms',
      'Train users on policies',
    ],
  },
];

// Shadow AI
export const mockShadowAI: types.ShadowAIResponse = {
  approvedProviders: ['Microsoft Copilot', 'ChatComposer'],
  violations: [
    {
      provider: 'ChatGPT (Unauthorized)',
      eventCount: 87,
      departments: ['Engineering', 'Product'],
      totalCost: 234.50,
    },
    {
      provider: 'Claude (Unauthorized)',
      eventCount: 52,
      departments: ['Sales', 'Marketing'],
      totalCost: 156.20,
    },
    {
      provider: 'Gemini (Unauthorized)',
      eventCount: 34,
      departments: ['Finance'],
      totalCost: 98.75,
    },
  ],
};

// Anomalies
export const mockAnomalies: types.AnomalyAlert[] = [
  {
    department: 'Engineering',
    period: '2026-04-07',
    metric: 'daily_cost',
    baselineValue: 3200,
    observedValue: 5842,
    zScore: 2.84,
    severity: 'high',
    explanation: 'Cost spike likely due to increased debugging activity and test runs',
  },
  {
    department: 'Product',
    period: '2026-04-06',
    metric: 'token_usage',
    baselineValue: 45000,
    observedValue: 78300,
    zScore: 2.12,
    severity: 'medium',
    explanation: 'Unusual token usage pattern, possibly from batch processing or data analysis',
  },
  {
    department: 'Sales',
    period: '2026-04-08',
    metric: 'event_count',
    baselineValue: 180,
    observedValue: 412,
    zScore: 3.21,
    severity: 'high',
    explanation: 'Event volume spike during customer onboarding campaign',
  },
];

// Scatter Points
export const mockScatterPoints: types.ScatterPoint[] = Array.from({ length: 30 }, (_, i) => {
  const departments = ['Engineering', 'Product', 'Sales', 'Marketing', 'Finance'];
  const providers = ['GPT-4o', 'Claude', 'Gemini', 'Mistral'];
  const severities: types.Severity[] = ['critical', 'high', 'medium'];

  return {
    conversationId: `conv_scatter_${i + 1}`,
    tokenCount: Math.floor(Math.random() * 200000) + 10000,
    findingCount: Math.floor(Math.random() * 8),
    provider: providers[Math.floor(Math.random() * providers.length)],
    cost: Math.random() * 500 + 10,
    department: departments[Math.floor(Math.random() * departments.length)],
    severity: severities[Math.floor(Math.random() * severities.length)],
  };
});

// Export all mock data
export const mockData = {
  dashboardSummary: mockDashboardSummary,
  complianceScore: mockComplianceScore,
  costByDepartment: mockCostByDepartment,
  costByModel: mockCostByModel,
  costTimeSeries: mockCostTimeSeries,
  severityDistribution: mockSeverityDistribution,
  findings: mockFindings,
  alerts: mockAlerts,
  modelMetrics: mockModelMetrics,
  slopsquattingStats: mockSlopsquattingStats,
  dataFlow: mockDataFlow,
  contextRisk: mockContextRisk,
  providerDPA: mockProviderDPA,
  recommendations: mockRecommendations,
  shadowAI: mockShadowAI,
  anomalies: mockAnomalies,
  scatterPoints: mockScatterPoints,
};
