from fastapi import APIRouter, Depends
from sqlalchemy import text

from app.infrastructure.database import async_session_factory
from app.auth.jwt import get_current_user

router = APIRouter()

@router.get("")
async def get_active_recommendations(current_user: dict = Depends(get_current_user)):
    """Fetch all active system recommendations generated by the Strands LLM."""
    async with async_session_factory() as session:
        query = text("""
            SELECT id, category, title, description, impact_score, target_audience, status, created_at
            FROM system_recommendations
            WHERE status = 'active'
            ORDER BY impact_score DESC, created_at DESC
        """)
        
        result = await session.execute(query)
        rows = result.fetchall()
        
        return [
            {
                "id": str(row.id),
                "category": row.category,
                "title": row.title,
                "description": row.description,
                "impact_score": row.impact_score,
                "target_audience": row.target_audience,
                "status": row.status,
                "created_at": row.created_at
            }
            for row in rows
        ]
